@startuml

title __DOMOTIX > CONTROLLER's Class Diagram__\n

namespace src.domotix.controller {
    class src.domotix.controller.Modificatore {
        {static} + aggiungiRegola()
        {static} - costruisciInfoDaSensore()
        {static} - aggiungiComponenteCostanteAntecedente()
        {static} + aggiungiComponenteAntecedente()
        {static} + aggiungiOperatoreLogico()
        {static} + rimuoviRegola()
        {static} + aggiungiAzioneConseguente()
    }

    class src.domotix.controller.OperazioniFinali {

    }

    class src.domotix.controller.OperazioniIniziali {

    }

    class src.domotix.controller.Recuperatore {
        {static} + getRegoleUnita()
        {static} + isInfoNumerica()
        {static} + getAntecedentiRegoleUnita()
        {static} + isModalitaParametrica()
        {static} + getNomiParametriModalita()
        {static} + getModalitaTutte()
    }

    class src.domotix.controller.Verificatore {
        {static} + checkValiditaOperatoreLogico()
    }

    class src.domotix.controller.TimerGestioneRegole {
        {static} + DEFAULT_DELAY : int
        {static} - instance : TimerGestioneRegole
        {static} + getInstance()
        - timer : Timer
        - delay : int
        + TimerGestioneRegole()
        + getDelay()
        + setDelay()
        + start()
        + stop()
        - action()
    }

    class src.domotix.controller.TimerRinfrescoDati {
        {static} + DEFAULT_DELAY : int
        {static} - instance : TimerRinfrescoDati
        {static} + getInstance()
        - timer : Timer
        - delay : int
        + TimerRinfrescoDati()
        + getDelay()
        + setDelay()
        + start()
        + stop()
        - action()
    }

    namespace util {
        class src.domotix.controller.util.StringUtil {
        }
    }
}

namespace src.domotix.model {

}

src.domotix.controller.Modificatore --> src.domotix.controller.util.StringUtil
src.domotix.controller.Modificatore --> src.domotix.controller.Recuperatore
src.domotix.controller.Modificatore --> src.domotix.controller.Verificatore
src.domotix.controller.Modificatore --> src.domotix.model

src.domotix.controller.Verificatore --> src.domotix.controller.Recuperatore
src.domotix.controller.Verificatore --> src.domotix.model

src.domotix.controller.Recuperatore --> src.domotix.model

src.domotix.controller.OperazioniIniziali --> src.domotix.model
src.domotix.controller.OperazioniIniziali --> src.domotix.view.MenuErroreApertura

src.domotix.controller.OperazioniFinali --> src.domotix.model
src.domotix.controller.OperazioniFinali --> src.domotix.view.MenuErroreChiusura

src.domotix.controller.TimerGestioneRegole --> src.domotix.model
src.domotix.controller.TimerRinfrescoDati --> src.domotix.model

@enduml
