@startuml

title __DOMOTIX > VIEW > MENUS's Class Diagram__\n

namespace src.domotix.view.menus {
    class src.domotix.view.menus.MenuErroreApertura {
    }

    class src.domotix.view.menus.MenuErroreChiusura {
    }

    class src.domotix.view.menus.MenuLogin {
    }

    namespace menuPrincipale {
        class src.domotix.view.menus.menuPrincipale.MenuFruitore {
        }

        class src.domotix.view.menus.menuPrincipale.MenuManutentore {
            {static} - SUCCESSO_INSERIMENTO_UNITA : String
            {static} - ERRORE_INSERIMENTO_UNITA : String
            {static} - SUCCESSO_RIMOZIONE_UNITA : String
            {static} - ERRORE_RIMOZIONE_UNITA : String
            {static} - NOMI_UNITA_IMMOBILIARI_ESISTENTI : String
            {static} - NOME_NUOVA_UNITA : String
            {static} - premenuUnita()
        }
    }

    namespace menuCategorie {
        class src.domotix.view.menus.menuCategorie.MenuCategorieF {
        }

        class src.domotix.view.menus.menuCategorie.MenuCategorieM {
        }

        namespace sensori {
            class src.domotix.view.menus.menuCategorie.sensori.MenuCategorieSensoriF {
            }

            class src.domotix.view.menus.menuCategorie.sensori.MenuCategorieSensoriM {
                {static} - TERMINATORE : String
                {static} - SUCCESSO_INSERIMENTO_INFO : String
                {static} - ERRORE_INSERIMENTO_INFO : String
                {static} - INSERIMENTO_NOME_INFO : String
                {static} - ALMENO_UNA_INFO : String
                {static} - IS_NUMERICA : String
            }
        }

        namespace attuatori {
            class src.domotix.view.menus.menuCategorie.attuatori.MenuCategorieAttuatoriF {
            }

            class src.domotix.view.menus.menuCategorie.attuatori.MenuCategorieAttuatoriM {
                {static} - IS_PARAMETRICA : String
                {static} - INSERIMENTO_NOME_PARAMETRO : String
                {static} - SUCCESSO_INSERIMENTO_PARAMETRO : String
                {static} - ERRORE_ALMENO_UN_PARAMETRO : String
                {static} - ERRORE_INSERIMENTO_PARAMETRO : String
                {static} - INSERIMENTO_VALORE_PARAMETRO : String
            }
        }
    }

    namespace menuUnita {
    }
}

src.domotix.view.menus.MenuLogin --> src.domotix.view.menus.menuPrincipale
src.domotix.view.menus.menuPrincipale.MenuManutentore --> src.domotix.view.menus.menuUnita.MenuUnitaM
src.domotix.view.menus.menuPrincipale.MenuFruitore --> src.domotix.view.menus.menuUnita.MenuUnitaF
src.domotix.view.menus.menuPrincipale.MenuManutentore --> src.domotix.view.menus.menuCategorie.MenuCategorieM
src.domotix.view.menus.menuPrincipale.MenuFruitore --> src.domotix.view.menus.menuCategorie.MenuCategorieF
src.domotix.view.menus.menuCategorie.MenuCategorieM --> src.domotix.view.menus.menuCategorie.attuatori.MenuCategorieAttuatoriM
src.domotix.view.menus.menuCategorie.MenuCategorieM --> src.domotix.view.menus.menuCategorie.sensori.MenuCategorieSensoriM
src.domotix.view.menus.menuCategorie.MenuCategorieF --> src.domotix.view.menus.menuCategorie.attuatori.MenuCategorieAttuatoriF
src.domotix.view.menus.menuCategorie.MenuCategorieF --> src.domotix.view.menus.menuCategorie.sensori.MenuCategorieSensoriF

src.domotix.view.menus.menuCategorie.attuatori.MenuCategorieAttuatoriM --> src.domotix.controller.Modificatore
src.domotix.view.menus.menuCategorie.attuatori.MenuCategorieAttuatoriM --> src.domotix.controller.Recuperatore
src.domotix.view.menus.menuCategorie.attuatori.MenuCategorieAttuatoriF --> src.domotix.controller.Recuperatore
src.domotix.view.menus.menuCategorie.sensori.MenuCategorieSensoriM --> src.domotix.controller.Modificatore
src.domotix.view.menus.menuCategorie.sensori.MenuCategorieSensoriM --> src.domotix.controller.Recuperatore
src.domotix.view.menus.menuCategorie.sensori.MenuCategorieSensoriF --> src.domotix.controller.Recuperatore
src.domotix.view.menus.menuPrincipale.MenuManutentore --> src.domotix.controller.Modificatore

@enduml
