@startuml

title __DOMOTIX > VIEW > MENUS's Class Diagram__\n

namespace src.domotix.view.menus {
    class src.domotix.view.menus.MenuErroreApertura {
    }

    class src.domotix.view.menus.MenuErroreChiusura {
    }

    class src.domotix.view.menus.MenuAzioniConflitto {
        {static} - NESSUNA : String
        {static} - TITOLO_ELIMINA : String
        {static} - TITOLO_ESEGUI : String
        {static} - AVVISA_PROSEGUIMENTO_DOPO_ELIMINA : String
        {static} - AVVISA_PROSEGUIMENTO_DOPO_ESEGUI : String
        {static} - menu : MyMenu
        {static} + avvia()
        {static} - premenuElimina()
        {static} - premenuEsegui()
    }

    class src.domotix.view.menus.MenuLogin {
    }

    namespace menuPrincipale {
        class src.domotix.view.menus.menuPrincipale.MenuFruitore {
            {static} - NESSUNA_AZIONE_PROGRAMMATA : String
        }

        class src.domotix.view.menus.menuPrincipale.MenuManutentore {
        }
    }

    namespace menuCategorie {
        class src.domotix.view.menus.menuCategorie.MenuCategorieF {
        }

        class src.domotix.view.menus.menuCategorie.MenuCategorieM {
        }

        namespace sensori {
            class src.domotix.view.menus.menuCategorie.sensori.MenuCategorieSensoriF {
            }

            class src.domotix.view.menus.menuCategorie.sensori.MenuCategorieSensoriM {
            }
        }

        namespace attuatori {
            class src.domotix.view.menus.menuCategorie.attuatori.MenuCategorieAttuatoriF {
            }

            class src.domotix.view.menus.menuCategorie.attuatori.MenuCategorieAttuatoriM {
            }
        }
    }

    namespace menuUnita {
    }
}

src.domotix.view.menus.MenuLogin --> src.domotix.view.menus.menuPrincipale
src.domotix.view.menus.menuPrincipale.MenuManutentore --> src.domotix.view.menus.menuUnita.MenuUnitaM
src.domotix.view.menus.menuPrincipale.MenuFruitore --> src.domotix.view.menus.menuUnita.MenuUnitaF
src.domotix.view.menus.menuPrincipale.MenuManutentore --> src.domotix.view.menus.menuCategorie.MenuCategorieM
src.domotix.view.menus.menuPrincipale.MenuFruitore --> src.domotix.view.menus.menuCategorie.MenuCategorieF
src.domotix.view.menus.menuCategorie.MenuCategorieM --> src.domotix.view.menus.menuCategorie.attuatori.MenuCategorieAttuatoriM
src.domotix.view.menus.menuCategorie.MenuCategorieM --> src.domotix.view.menus.menuCategorie.sensori.MenuCategorieSensoriM
src.domotix.view.menus.menuCategorie.MenuCategorieF --> src.domotix.view.menus.menuCategorie.attuatori.MenuCategorieAttuatoriF
src.domotix.view.menus.menuCategorie.MenuCategorieF --> src.domotix.view.menus.menuCategorie.sensori.MenuCategorieSensoriF

src.domotix.view.menus.menuCategorie.attuatori.MenuCategorieAttuatoriM --> src.domotix.controller.Modificatore
src.domotix.view.menus.menuCategorie.attuatori.MenuCategorieAttuatoriM --> src.domotix.controller.Recuperatore
src.domotix.view.menus.menuCategorie.attuatori.MenuCategorieAttuatoriF --> src.domotix.controller.Recuperatore
src.domotix.view.menus.menuCategorie.sensori.MenuCategorieSensoriM --> src.domotix.controller.Modificatore
src.domotix.view.menus.menuCategorie.sensori.MenuCategorieSensoriM --> src.domotix.controller.Recuperatore
src.domotix.view.menus.menuCategorie.sensori.MenuCategorieSensoriF --> src.domotix.controller.Recuperatore
src.domotix.view.menus.menuPrincipale.MenuManutentore --> src.domotix.controller.Modificatore

@enduml
