@startuml

title __DOMOTIX > MODEL > IO's Class Diagram__\n

namespace src.domotix.model {
    namespace util {
    }

    namespace io {
        interface src.domotix.model.io.LetturaDatiSalvati {
            {abstract} + getNomiInformazioniRilevabili()
            {abstract} + leggiInfoRilevabile()
        }

        abstract class src.domotix.model.io.LetturaDatiSalvatiAdapter {
            + getNomiInformazioniRilevabili()
            + leggiInfoRilevabile()
        }

        interface src.domotix.model.io.RimozioneDatiSalvati {
            {abstract} + rimuoviInfoRilevabile()
            {abstract} + sincronizzaInfoRilevabile()
        }

        class src.domotix.model.io.RimozioneDatiSalvatiAdapter {
            + rimuoviInfoRilevabile()
            + sincronizzaInfoRilevabile()
        }

        interface src.domotix.model.io.ScritturaDatiSalvati {
            {abstract} + salva()
        }

        class src.domotix.model.io.ScritturaDatiSalvatiAdapter {
            + salva()
        }

        namespace datilocali {
            enum src.domotix.model.io.datilocali.LettoriXML {
                PARAMETRO_MODALITA
                INFORMAZIONE_RILEVABILE
            }

            interface src.domotix.model.io.datilocali.LettoriXML.IstanziatoreXML {
            }

            class src.domotix.model.io.datilocali.LetturaDatiLocali {
                + getNomiInformazioniRilevabili()
                + leggiInfoRilevabile()
            }

            class src.domotix.model.io.datilocali.PercorsiFile {
                + getCartellaInformazioneRilevabile()
                + getNomiInformazioniRilevabili()
                + getPercorsoInformazioneRilevabile()
            }

            class src.domotix.model.io.datilocali.RimozioneDatiLocali {
                + rimuoviInfoRilevabile()
                + sincronizzaInfoRilevabile()
            }

            enum src.domotix.model.io.datilocali.ScrittoriXML {
                PARAMETRO_MODALITA
                INFORMAZIONE_RILEVABILE
            }

            interface src.domotix.model.io.datilocali.ScrittoriXML.CompilatoreXML {
            }

            class src.domotix.model.io.datilocali.ScritturaDatiLocali {
                + salva()
            }
        }
    }
}
  

src.domotix.model.io.LetturaDatiSalvatiAdapter .up.|> src.domotix.model.io.LetturaDatiSalvati
src.domotix.model.io.RimozioneDatiSalvatiAdapter .up.|> src.domotix.model.io.RimozioneDatiSalvati
src.domotix.model.io.ScritturaDatiSalvatiAdapter .up.|> src.domotix.model.io.ScritturaDatiSalvati

src.domotix.model.io.datilocali.LetturaDatiLocali -up-|> src.domotix.model.io.LetturaDatiSalvatiAdapter
src.domotix.model.io.datilocali.RimozioneDatiLocali -up-|> src.domotix.model.io.RimozioneDatiSalvatiAdapter
src.domotix.model.io.datilocali.ScritturaDatiLocali -up-|> src.domotix.model.io.ScritturaDatiSalvatiAdapter

src.domotix.model.io.datilocali.LettoriXML "1" o-- "1" src.domotix.model.io.datilocali.LettoriXML.IstanziatoreXML : istanziatore
src.domotix.model.io.datilocali.LettoriXML +-down- src.domotix.model.io.datilocali.LettoriXML.IstanziatoreXML : contiene >
src.domotix.model.io.datilocali.ScrittoriXML "1" o-- "1" src.domotix.model.io.datilocali.ScrittoriXML.CompilatoreXML : compilatore
src.domotix.model.io.datilocali.ScrittoriXML +-down- src.domotix.model.io.datilocali.ScrittoriXML.CompilatoreXML : contiene >

src.domotix.model.io.datilocali.PercorsiFile -- src.domotix.model.util.Costanti : usa >
src.domotix.model.io.datilocali.LettoriXML -- src.domotix.model.util.Costanti : usa >
src.domotix.model.io.datilocali.ScrittoriXML -- src.domotix.model.util.Costanti : usa >
src.domotix.model.io.datilocali.LetturaDatiLocali -- src.domotix.model.util.Costanti : usa >
src.domotix.model.io.datilocali.LetturaDatiLocali -- src.domotix.model.io.datilocali.LettoriXML : usa >
src.domotix.model.io.datilocali.ScritturaDatiLocali -- src.domotix.model.io.datilocali.ScrittoriXML : usa >

src.domotix.model.io.datilocali.LettoriXML -- src.domotix.model.io.LetturaDatiSalvati
src.domotix.model.io.datilocali.ScrittoriXML -- src.domotix.model.io.ScritturaDatiSalvati
src.domotix.model.io.datilocali.RimozioneDatiLocali -- src.domotix.model.io.RimozioneDatiSalvati

@enduml
