@startuml

title __DOMOTIX > MODEL > UTIL's Class Diagram__\n

namespace src.domotix.model {
    namespace util {
        class src.domotix.model.util.Costanti {
        }

        class src.domotix.model.util.ElencoDispositivi {
        }

        interface src.domotix.model.util.ObservableList {
        }

        interface src.domotix.model.util.ObserverList {
        }

        class src.domotix.model.util.SommarioDispositivi {
        }
    }

    namespace bean {
        namespace device {
            abstract class Dispositivo {
            }
        }
    }
}



src.domotix.model.util.ElencoDispositivi ..|> src.domotix.model.util.ObservableList
src.domotix.model.util.SommarioDispositivi ..|> src.domotix.model.util.ObserverList
src.domotix.model.util.ElencoDispositivi "*" o--> "1" src.domotix.model.bean.device.Dispositivo : elenco
src.domotix.model.util.SommarioDispositivi "*" o--> "1" src.domotix.model.bean.device.Dispositivo : elenco

@enduml
